//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.05.09 at 11:11:02 AM CEST
//


package org.taktik.icure.asynclogic.be.inami.importer.domain;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nomen_code" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_code_num" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="dbegin" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="dend" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="nomen_code_cat" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_code_cat_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="65"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_code_cat_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="65"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_n" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_n_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="65"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_n_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="65"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1800"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1800"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_chap" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_chap_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="155"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_chap_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="155"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_art" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_art_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="600"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_art_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="600"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_sub_art" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_sub_art_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_sub_art_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ambhos_pat_cat" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ambhos_pat_cat_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ambhos_pat_cat_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_G" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_sector" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_sector_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="155"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_sector_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="155"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_a" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_a_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="155"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_a_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="155"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_a_det" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_a_det_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="155"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_grp_a_det_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="155"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="key_letter1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="key_letter_index1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="key_coeff1" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="key_letter1_value" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="key_letter2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="key_letter_index2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="key_coeff2" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="key_letter2_value" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="key_letter3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="key_letter_index3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="key_coeff3" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="key_letter3_value" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="nomen_long_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_long_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_short_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nomen_short_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="corresp_pat_cat_real" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="combi_pat_cat_real" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="corresp_pat_cat_theor" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="combi_pat_cat_theor" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dbegin_fee_base" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="dend_fee_base" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="fee_base_code" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="fee_base_code_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fee_base_code_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fee_base" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="file_creation_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="file_applic_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nomenCode",
    "nomenCodeNum",
    "dbegin",
    "dend",
    "nomenCodeCat",
    "nomenCodeCatDescNl",
    "nomenCodeCatDescFr",
    "nomenGrpN",
    "nomenGrpNDescNl",
    "nomenGrpNDescFr",
    "nomenDescNl",
    "nomenDescFr",
    "nomenChap",
    "nomenChapDescNl",
    "nomenChapDescFr",
    "nomenArt",
    "nomenArtDescNl",
    "nomenArtDescFr",
    "nomenSubArt",
    "nomenSubArtDescNl",
    "nomenSubArtDescFr",
    "ambhosPatCat",
    "ambhosPatCatDescNl",
    "ambhosPatCatDescFr",
    "nomenGrpG",
    "nomenGrpSector",
    "nomenGrpSectorDescNl",
    "nomenGrpSectorDescFr",
    "nomenGrpA",
    "nomenGrpADescNl",
    "nomenGrpADescFr",
    "nomenGrpADet",
    "nomenGrpADetDescNl",
    "nomenGrpADetDescFr",
    "keyLetter1",
    "keyLetterIndex1",
    "keyCoeff1",
    "keyLetter1Value",
    "keyLetter2",
    "keyLetterIndex2",
    "keyCoeff2",
    "keyLetter2Value",
    "keyLetter3",
    "keyLetterIndex3",
    "keyCoeff3",
    "keyLetter3Value",
    "nomenLongDescNl",
    "nomenLongDescFr",
    "nomenShortDescNl",
    "nomenShortDescFr",
    "correspPatCatReal",
    "combiPatCatReal",
    "correspPatCatTheor",
    "combiPatCatTheor",
    "dbeginFeeBase",
    "dendFeeBase",
    "feeBaseCode",
    "feeBaseCodeDescNl",
    "feeBaseCodeDescFr",
    "feeBase",
    "fileCreationDate",
    "fileApplicDate"
})
@XmlRootElement(name = "NOMEN_SUMMARY_EXT")
public class NomenSummaryExt {

    @XmlElement(name = "nomen_code")
    protected String nomenCode;
    @XmlElement(name = "nomen_code_num")
    protected Double nomenCodeNum;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dbegin;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dend;
    @XmlElement(name = "nomen_code_cat")
    protected String nomenCodeCat;
    @XmlElement(name = "nomen_code_cat_desc_nl")
    protected String nomenCodeCatDescNl;
    @XmlElement(name = "nomen_code_cat_desc_fr")
    protected String nomenCodeCatDescFr;
    @XmlElement(name = "nomen_grp_n")
    protected String nomenGrpN;
    @XmlElement(name = "nomen_grp_n_desc_nl")
    protected String nomenGrpNDescNl;
    @XmlElement(name = "nomen_grp_n_desc_fr")
    protected String nomenGrpNDescFr;
    @XmlElement(name = "nomen_desc_nl")
    protected String nomenDescNl;
    @XmlElement(name = "nomen_desc_fr")
    protected String nomenDescFr;
    @XmlElement(name = "nomen_chap")
    protected String nomenChap;
    @XmlElement(name = "nomen_chap_desc_nl")
    protected String nomenChapDescNl;
    @XmlElement(name = "nomen_chap_desc_fr")
    protected String nomenChapDescFr;
    @XmlElement(name = "nomen_art")
    protected String nomenArt;
    @XmlElement(name = "nomen_art_desc_nl")
    protected String nomenArtDescNl;
    @XmlElement(name = "nomen_art_desc_fr")
    protected String nomenArtDescFr;
    @XmlElement(name = "nomen_sub_art")
    protected String nomenSubArt;
    @XmlElement(name = "nomen_sub_art_desc_nl")
    protected String nomenSubArtDescNl;
    @XmlElement(name = "nomen_sub_art_desc_fr")
    protected String nomenSubArtDescFr;
    @XmlElement(name = "ambhos_pat_cat")
    protected String ambhosPatCat;
    @XmlElement(name = "ambhos_pat_cat_desc_nl")
    protected String ambhosPatCatDescNl;
    @XmlElement(name = "ambhos_pat_cat_desc_fr")
    protected String ambhosPatCatDescFr;
    @XmlElement(name = "nomen_grp_G")
    protected String nomenGrpG;
    @XmlElement(name = "nomen_grp_sector")
    protected String nomenGrpSector;
    @XmlElement(name = "nomen_grp_sector_desc_nl")
    protected String nomenGrpSectorDescNl;
    @XmlElement(name = "nomen_grp_sector_desc_fr")
    protected String nomenGrpSectorDescFr;
    @XmlElement(name = "nomen_grp_a")
    protected String nomenGrpA;
    @XmlElement(name = "nomen_grp_a_desc_nl")
    protected String nomenGrpADescNl;
    @XmlElement(name = "nomen_grp_a_desc_fr")
    protected String nomenGrpADescFr;
    @XmlElement(name = "nomen_grp_a_det")
    protected String nomenGrpADet;
    @XmlElement(name = "nomen_grp_a_det_desc_nl")
    protected String nomenGrpADetDescNl;
    @XmlElement(name = "nomen_grp_a_det_desc_fr")
    protected String nomenGrpADetDescFr;
    @XmlElement(name = "key_letter1")
    protected String keyLetter1;
    @XmlElement(name = "key_letter_index1")
    protected String keyLetterIndex1;
    @XmlElement(name = "key_coeff1")
    protected Double keyCoeff1;
    @XmlElement(name = "key_letter1_value")
    protected Double keyLetter1Value;
    @XmlElement(name = "key_letter2")
    protected String keyLetter2;
    @XmlElement(name = "key_letter_index2")
    protected String keyLetterIndex2;
    @XmlElement(name = "key_coeff2")
    protected Double keyCoeff2;
    @XmlElement(name = "key_letter2_value")
    protected Double keyLetter2Value;
    @XmlElement(name = "key_letter3")
    protected String keyLetter3;
    @XmlElement(name = "key_letter_index3")
    protected String keyLetterIndex3;
    @XmlElement(name = "key_coeff3")
    protected Double keyCoeff3;
    @XmlElement(name = "key_letter3_value")
    protected Double keyLetter3Value;
    @XmlElement(name = "nomen_long_desc_nl")
    protected String nomenLongDescNl;
    @XmlElement(name = "nomen_long_desc_fr")
    protected String nomenLongDescFr;
    @XmlElement(name = "nomen_short_desc_nl")
    protected String nomenShortDescNl;
    @XmlElement(name = "nomen_short_desc_fr")
    protected String nomenShortDescFr;
    @XmlElement(name = "corresp_pat_cat_real")
    protected String correspPatCatReal;
    @XmlElement(name = "combi_pat_cat_real")
    protected String combiPatCatReal;
    @XmlElement(name = "corresp_pat_cat_theor")
    protected String correspPatCatTheor;
    @XmlElement(name = "combi_pat_cat_theor")
    protected String combiPatCatTheor;
    @XmlElement(name = "dbegin_fee_base")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dbeginFeeBase;
    @XmlElement(name = "dend_fee_base")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dendFeeBase;
    @XmlElement(name = "fee_base_code")
    protected Double feeBaseCode;
    @XmlElement(name = "fee_base_code_desc_nl")
    protected String feeBaseCodeDescNl;
    @XmlElement(name = "fee_base_code_desc_fr")
    protected String feeBaseCodeDescFr;
    @XmlElement(name = "fee_base")
    protected Double feeBase;
    @XmlElement(name = "file_creation_date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fileCreationDate;
    @XmlElement(name = "file_applic_date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fileApplicDate;

    /**
     * Gets the value of the nomenCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenCode() {
        return nomenCode;
    }

    /**
     * Sets the value of the nomenCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenCode(String value) {
        this.nomenCode = value;
    }

    /**
     * Gets the value of the nomenCodeNum property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getNomenCodeNum() {
        return nomenCodeNum;
    }

    /**
     * Sets the value of the nomenCodeNum property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setNomenCodeNum(Double value) {
        this.nomenCodeNum = value;
    }

    /**
     * Gets the value of the dbegin property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDbegin() {
        return dbegin;
    }

    /**
     * Sets the value of the dbegin property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDbegin(XMLGregorianCalendar value) {
        this.dbegin = value;
    }

    /**
     * Gets the value of the dend property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDend() {
        return dend;
    }

    /**
     * Sets the value of the dend property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDend(XMLGregorianCalendar value) {
        this.dend = value;
    }

    /**
     * Gets the value of the nomenCodeCat property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenCodeCat() {
        return nomenCodeCat;
    }

    /**
     * Sets the value of the nomenCodeCat property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenCodeCat(String value) {
        this.nomenCodeCat = value;
    }

    /**
     * Gets the value of the nomenCodeCatDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenCodeCatDescNl() {
        return nomenCodeCatDescNl;
    }

    /**
     * Sets the value of the nomenCodeCatDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenCodeCatDescNl(String value) {
        this.nomenCodeCatDescNl = value;
    }

    /**
     * Gets the value of the nomenCodeCatDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenCodeCatDescFr() {
        return nomenCodeCatDescFr;
    }

    /**
     * Sets the value of the nomenCodeCatDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenCodeCatDescFr(String value) {
        this.nomenCodeCatDescFr = value;
    }

    /**
     * Gets the value of the nomenGrpN property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpN() {
        return nomenGrpN;
    }

    /**
     * Sets the value of the nomenGrpN property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpN(String value) {
        this.nomenGrpN = value;
    }

    /**
     * Gets the value of the nomenGrpNDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpNDescNl() {
        return nomenGrpNDescNl;
    }

    /**
     * Sets the value of the nomenGrpNDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpNDescNl(String value) {
        this.nomenGrpNDescNl = value;
    }

    /**
     * Gets the value of the nomenGrpNDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpNDescFr() {
        return nomenGrpNDescFr;
    }

    /**
     * Sets the value of the nomenGrpNDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpNDescFr(String value) {
        this.nomenGrpNDescFr = value;
    }

    /**
     * Gets the value of the nomenDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenDescNl() {
        return nomenDescNl;
    }

    /**
     * Sets the value of the nomenDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenDescNl(String value) {
        this.nomenDescNl = value;
    }

    /**
     * Gets the value of the nomenDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenDescFr() {
        return nomenDescFr;
    }

    /**
     * Sets the value of the nomenDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenDescFr(String value) {
        this.nomenDescFr = value;
    }

    /**
     * Gets the value of the nomenChap property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenChap() {
        return nomenChap;
    }

    /**
     * Sets the value of the nomenChap property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenChap(String value) {
        this.nomenChap = value;
    }

    /**
     * Gets the value of the nomenChapDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenChapDescNl() {
        return nomenChapDescNl;
    }

    /**
     * Sets the value of the nomenChapDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenChapDescNl(String value) {
        this.nomenChapDescNl = value;
    }

    /**
     * Gets the value of the nomenChapDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenChapDescFr() {
        return nomenChapDescFr;
    }

    /**
     * Sets the value of the nomenChapDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenChapDescFr(String value) {
        this.nomenChapDescFr = value;
    }

    /**
     * Gets the value of the nomenArt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenArt() {
        return nomenArt;
    }

    /**
     * Sets the value of the nomenArt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenArt(String value) {
        this.nomenArt = value;
    }

    /**
     * Gets the value of the nomenArtDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenArtDescNl() {
        return nomenArtDescNl;
    }

    /**
     * Sets the value of the nomenArtDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenArtDescNl(String value) {
        this.nomenArtDescNl = value;
    }

    /**
     * Gets the value of the nomenArtDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenArtDescFr() {
        return nomenArtDescFr;
    }

    /**
     * Sets the value of the nomenArtDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenArtDescFr(String value) {
        this.nomenArtDescFr = value;
    }

    /**
     * Gets the value of the nomenSubArt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenSubArt() {
        return nomenSubArt;
    }

    /**
     * Sets the value of the nomenSubArt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenSubArt(String value) {
        this.nomenSubArt = value;
    }

    /**
     * Gets the value of the nomenSubArtDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenSubArtDescNl() {
        return nomenSubArtDescNl;
    }

    /**
     * Sets the value of the nomenSubArtDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenSubArtDescNl(String value) {
        this.nomenSubArtDescNl = value;
    }

    /**
     * Gets the value of the nomenSubArtDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenSubArtDescFr() {
        return nomenSubArtDescFr;
    }

    /**
     * Sets the value of the nomenSubArtDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenSubArtDescFr(String value) {
        this.nomenSubArtDescFr = value;
    }

    /**
     * Gets the value of the ambhosPatCat property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAmbhosPatCat() {
        return ambhosPatCat;
    }

    /**
     * Sets the value of the ambhosPatCat property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAmbhosPatCat(String value) {
        this.ambhosPatCat = value;
    }

    /**
     * Gets the value of the ambhosPatCatDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAmbhosPatCatDescNl() {
        return ambhosPatCatDescNl;
    }

    /**
     * Sets the value of the ambhosPatCatDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAmbhosPatCatDescNl(String value) {
        this.ambhosPatCatDescNl = value;
    }

    /**
     * Gets the value of the ambhosPatCatDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAmbhosPatCatDescFr() {
        return ambhosPatCatDescFr;
    }

    /**
     * Sets the value of the ambhosPatCatDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAmbhosPatCatDescFr(String value) {
        this.ambhosPatCatDescFr = value;
    }

    /**
     * Gets the value of the nomenGrpG property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpG() {
        return nomenGrpG;
    }

    /**
     * Sets the value of the nomenGrpG property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpG(String value) {
        this.nomenGrpG = value;
    }

    /**
     * Gets the value of the nomenGrpSector property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpSector() {
        return nomenGrpSector;
    }

    /**
     * Sets the value of the nomenGrpSector property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpSector(String value) {
        this.nomenGrpSector = value;
    }

    /**
     * Gets the value of the nomenGrpSectorDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpSectorDescNl() {
        return nomenGrpSectorDescNl;
    }

    /**
     * Sets the value of the nomenGrpSectorDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpSectorDescNl(String value) {
        this.nomenGrpSectorDescNl = value;
    }

    /**
     * Gets the value of the nomenGrpSectorDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpSectorDescFr() {
        return nomenGrpSectorDescFr;
    }

    /**
     * Sets the value of the nomenGrpSectorDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpSectorDescFr(String value) {
        this.nomenGrpSectorDescFr = value;
    }

    /**
     * Gets the value of the nomenGrpA property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpA() {
        return nomenGrpA;
    }

    /**
     * Sets the value of the nomenGrpA property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpA(String value) {
        this.nomenGrpA = value;
    }

    /**
     * Gets the value of the nomenGrpADescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpADescNl() {
        return nomenGrpADescNl;
    }

    /**
     * Sets the value of the nomenGrpADescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpADescNl(String value) {
        this.nomenGrpADescNl = value;
    }

    /**
     * Gets the value of the nomenGrpADescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpADescFr() {
        return nomenGrpADescFr;
    }

    /**
     * Sets the value of the nomenGrpADescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpADescFr(String value) {
        this.nomenGrpADescFr = value;
    }

    /**
     * Gets the value of the nomenGrpADet property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpADet() {
        return nomenGrpADet;
    }

    /**
     * Sets the value of the nomenGrpADet property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpADet(String value) {
        this.nomenGrpADet = value;
    }

    /**
     * Gets the value of the nomenGrpADetDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpADetDescNl() {
        return nomenGrpADetDescNl;
    }

    /**
     * Sets the value of the nomenGrpADetDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpADetDescNl(String value) {
        this.nomenGrpADetDescNl = value;
    }

    /**
     * Gets the value of the nomenGrpADetDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenGrpADetDescFr() {
        return nomenGrpADetDescFr;
    }

    /**
     * Sets the value of the nomenGrpADetDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenGrpADetDescFr(String value) {
        this.nomenGrpADetDescFr = value;
    }

    /**
     * Gets the value of the keyLetter1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKeyLetter1() {
        return keyLetter1;
    }

    /**
     * Sets the value of the keyLetter1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKeyLetter1(String value) {
        this.keyLetter1 = value;
    }

    /**
     * Gets the value of the keyLetterIndex1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKeyLetterIndex1() {
        return keyLetterIndex1;
    }

    /**
     * Sets the value of the keyLetterIndex1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKeyLetterIndex1(String value) {
        this.keyLetterIndex1 = value;
    }

    /**
     * Gets the value of the keyCoeff1 property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getKeyCoeff1() {
        return keyCoeff1;
    }

    /**
     * Sets the value of the keyCoeff1 property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setKeyCoeff1(Double value) {
        this.keyCoeff1 = value;
    }

    /**
     * Gets the value of the keyLetter1Value property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getKeyLetter1Value() {
        return keyLetter1Value;
    }

    /**
     * Sets the value of the keyLetter1Value property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setKeyLetter1Value(Double value) {
        this.keyLetter1Value = value;
    }

    /**
     * Gets the value of the keyLetter2 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKeyLetter2() {
        return keyLetter2;
    }

    /**
     * Sets the value of the keyLetter2 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKeyLetter2(String value) {
        this.keyLetter2 = value;
    }

    /**
     * Gets the value of the keyLetterIndex2 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKeyLetterIndex2() {
        return keyLetterIndex2;
    }

    /**
     * Sets the value of the keyLetterIndex2 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKeyLetterIndex2(String value) {
        this.keyLetterIndex2 = value;
    }

    /**
     * Gets the value of the keyCoeff2 property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getKeyCoeff2() {
        return keyCoeff2;
    }

    /**
     * Sets the value of the keyCoeff2 property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setKeyCoeff2(Double value) {
        this.keyCoeff2 = value;
    }

    /**
     * Gets the value of the keyLetter2Value property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getKeyLetter2Value() {
        return keyLetter2Value;
    }

    /**
     * Sets the value of the keyLetter2Value property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setKeyLetter2Value(Double value) {
        this.keyLetter2Value = value;
    }

    /**
     * Gets the value of the keyLetter3 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKeyLetter3() {
        return keyLetter3;
    }

    /**
     * Sets the value of the keyLetter3 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKeyLetter3(String value) {
        this.keyLetter3 = value;
    }

    /**
     * Gets the value of the keyLetterIndex3 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKeyLetterIndex3() {
        return keyLetterIndex3;
    }

    /**
     * Sets the value of the keyLetterIndex3 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKeyLetterIndex3(String value) {
        this.keyLetterIndex3 = value;
    }

    /**
     * Gets the value of the keyCoeff3 property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getKeyCoeff3() {
        return keyCoeff3;
    }

    /**
     * Sets the value of the keyCoeff3 property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setKeyCoeff3(Double value) {
        this.keyCoeff3 = value;
    }

    /**
     * Gets the value of the keyLetter3Value property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getKeyLetter3Value() {
        return keyLetter3Value;
    }

    /**
     * Sets the value of the keyLetter3Value property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setKeyLetter3Value(Double value) {
        this.keyLetter3Value = value;
    }

    /**
     * Gets the value of the nomenLongDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenLongDescNl() {
        return nomenLongDescNl;
    }

    /**
     * Sets the value of the nomenLongDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenLongDescNl(String value) {
        this.nomenLongDescNl = value;
    }

    /**
     * Gets the value of the nomenLongDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenLongDescFr() {
        return nomenLongDescFr;
    }

    /**
     * Sets the value of the nomenLongDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenLongDescFr(String value) {
        this.nomenLongDescFr = value;
    }

    /**
     * Gets the value of the nomenShortDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenShortDescNl() {
        return nomenShortDescNl;
    }

    /**
     * Sets the value of the nomenShortDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenShortDescNl(String value) {
        this.nomenShortDescNl = value;
    }

    /**
     * Gets the value of the nomenShortDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenShortDescFr() {
        return nomenShortDescFr;
    }

    /**
     * Sets the value of the nomenShortDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenShortDescFr(String value) {
        this.nomenShortDescFr = value;
    }

    /**
     * Gets the value of the correspPatCatReal property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCorrespPatCatReal() {
        return correspPatCatReal;
    }

    /**
     * Sets the value of the correspPatCatReal property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCorrespPatCatReal(String value) {
        this.correspPatCatReal = value;
    }

    /**
     * Gets the value of the combiPatCatReal property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCombiPatCatReal() {
        return combiPatCatReal;
    }

    /**
     * Sets the value of the combiPatCatReal property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCombiPatCatReal(String value) {
        this.combiPatCatReal = value;
    }

    /**
     * Gets the value of the correspPatCatTheor property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCorrespPatCatTheor() {
        return correspPatCatTheor;
    }

    /**
     * Sets the value of the correspPatCatTheor property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCorrespPatCatTheor(String value) {
        this.correspPatCatTheor = value;
    }

    /**
     * Gets the value of the combiPatCatTheor property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCombiPatCatTheor() {
        return combiPatCatTheor;
    }

    /**
     * Sets the value of the combiPatCatTheor property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCombiPatCatTheor(String value) {
        this.combiPatCatTheor = value;
    }

    /**
     * Gets the value of the dbeginFeeBase property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDbeginFeeBase() {
        return dbeginFeeBase;
    }

    /**
     * Sets the value of the dbeginFeeBase property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDbeginFeeBase(XMLGregorianCalendar value) {
        this.dbeginFeeBase = value;
    }

    /**
     * Gets the value of the dendFeeBase property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDendFeeBase() {
        return dendFeeBase;
    }

    /**
     * Sets the value of the dendFeeBase property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDendFeeBase(XMLGregorianCalendar value) {
        this.dendFeeBase = value;
    }

    /**
     * Gets the value of the feeBaseCode property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getFeeBaseCode() {
        return feeBaseCode;
    }

    /**
     * Sets the value of the feeBaseCode property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setFeeBaseCode(Double value) {
        this.feeBaseCode = value;
    }

    /**
     * Gets the value of the feeBaseCodeDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFeeBaseCodeDescNl() {
        return feeBaseCodeDescNl;
    }

    /**
     * Sets the value of the feeBaseCodeDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFeeBaseCodeDescNl(String value) {
        this.feeBaseCodeDescNl = value;
    }

    /**
     * Gets the value of the feeBaseCodeDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFeeBaseCodeDescFr() {
        return feeBaseCodeDescFr;
    }

    /**
     * Sets the value of the feeBaseCodeDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFeeBaseCodeDescFr(String value) {
        this.feeBaseCodeDescFr = value;
    }

    /**
     * Gets the value of the feeBase property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getFeeBase() {
        return feeBase;
    }

    /**
     * Sets the value of the feeBase property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setFeeBase(Double value) {
        this.feeBase = value;
    }

    /**
     * Gets the value of the fileCreationDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFileCreationDate() {
        return fileCreationDate;
    }

    /**
     * Sets the value of the fileCreationDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setFileCreationDate(XMLGregorianCalendar value) {
        this.fileCreationDate = value;
    }

    /**
     * Gets the value of the fileApplicDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFileApplicDate() {
        return fileApplicDate;
    }

    /**
     * Sets the value of the fileApplicDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setFileApplicDate(XMLGregorianCalendar value) {
        this.fileApplicDate = value;
    }

}
