//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.05.09 at 11:12:21 AM CEST
//


package org.taktik.icure.asynclogic.be.inami.importer.domain;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fee_code" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="fee_code_cat" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fee_code_desc_nl" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fee_code_desc_fr" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "feeCode",
    "feeCodeCat",
    "feeCodeDescNl",
    "feeCodeDescFr"
})
@XmlRootElement(name = "NOMEN_FEECODES")
public class NomenFeeCodes {

    @XmlElement(name = "fee_code")
    protected Integer feeCode;
    @XmlElement(name = "fee_code_cat")
    protected String feeCodeCat;
    @XmlElement(name = "fee_code_desc_nl")
    protected String feeCodeDescNl;
    @XmlElement(name = "fee_code_desc_fr")
    protected String feeCodeDescFr;

    /**
     * Gets the value of the feeCode property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getFeeCode() {
        return feeCode;
    }

    /**
     * Sets the value of the feeCode property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setFeeCode(Integer value) {
        this.feeCode = value;
    }

    /**
     * Gets the value of the feeCodeCat property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFeeCodeCat() {
        return feeCodeCat;
    }

    /**
     * Sets the value of the feeCodeCat property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFeeCodeCat(String value) {
        this.feeCodeCat = value;
    }

    /**
     * Gets the value of the feeCodeDescNl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFeeCodeDescNl() {
        return feeCodeDescNl;
    }

    /**
     * Sets the value of the feeCodeDescNl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFeeCodeDescNl(String value) {
        this.feeCodeDescNl = value;
    }

    /**
     * Gets the value of the feeCodeDescFr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFeeCodeDescFr() {
        return feeCodeDescFr;
    }

    /**
     * Sets the value of the feeCodeDescFr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFeeCodeDescFr(String value) {
        this.feeCodeDescFr = value;
    }

}
