//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.05.09 at 11:13:54 AM CEST
//


package org.taktik.icure.asynclogic.be.inami.importer.domain;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nomen_code" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dbegin_fee" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="dend_fee" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="fee_code" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="fee" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="AUTHORITY_ID" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nomenCode",
    "dbeginFee",
    "dendFee",
    "feeCode",
    "fee",
    "authorityid"
})
@XmlRootElement(name = "NOMEN_CODE_FEE_LIM")
public class NomenCodeFeeLim {

    @XmlElement(name = "nomen_code")
    protected String nomenCode;
    @XmlElement(name = "dbegin_fee")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dbeginFee;
    @XmlElement(name = "dend_fee")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dendFee;
    @XmlElement(name = "fee_code")
    protected Integer feeCode;
    protected Double fee;
    @XmlElement(name = "AUTHORITY_ID")
    protected Double authorityid;

    /**
     * Gets the value of the nomenCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNomenCode() {
        return nomenCode;
    }

    /**
     * Sets the value of the nomenCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNomenCode(String value) {
        this.nomenCode = value;
    }

    /**
     * Gets the value of the dbeginFee property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDbeginFee() {
        return dbeginFee;
    }

    /**
     * Sets the value of the dbeginFee property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDbeginFee(XMLGregorianCalendar value) {
        this.dbeginFee = value;
    }

    /**
     * Gets the value of the dendFee property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDendFee() {
        return dendFee;
    }

    /**
     * Sets the value of the dendFee property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDendFee(XMLGregorianCalendar value) {
        this.dendFee = value;
    }

    /**
     * Gets the value of the feeCode property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getFeeCode() {
        return feeCode;
    }

    /**
     * Sets the value of the feeCode property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setFeeCode(Integer value) {
        this.feeCode = value;
    }

    /**
     * Gets the value of the fee property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getFee() {
        return fee;
    }

    /**
     * Sets the value of the fee property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setFee(Double value) {
        this.fee = value;
    }

    /**
     * Gets the value of the authorityid property.
     *
     * @return
     *     possible object is
     *     {@link Double }
     *
     */
    public Double getAUTHORITYID() {
        return authorityid;
    }

    /**
     * Sets the value of the authorityid property.
     *
     * @param value
     *     allowed object is
     *     {@link Double }
     *
     */
    public void setAUTHORITYID(Double value) {
        this.authorityid = value;
    }

}
