//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.05.09 at 11:13:54 AM CEST
//


package org.taktik.icure.asynclogic.be.inami.importer.domain;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.taktik.icure.asynclogic.be.inami.importer.domain package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.taktik.icure.asynclogic.be.inami.importer.domain
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Table }
     *
     */
    public Table createTABLE() {
        return new Table();
    }

    /**
     * Create an instance of {@link NomenCodeFeeLim }
     *
     */
    public NomenCodeFeeLim createNOMENCODEFEELIM() {
        return new NomenCodeFeeLim();
    }

    /**
     * Create an instance of {@link NomenFeeCodes }
     *
     */
    public NomenFeeCodes createNOMENFEECODES() {
        return new NomenFeeCodes();
    }

    /**
     * Create an instance of {@link NomenSummaryExt }
     *
     */
    public NomenSummaryExt createNOMENSUMMARYEXT() {
        return new NomenSummaryExt();
    }

	public NomenFeeCodesCat createNOMENFEECODESCAT() {
		return new NomenFeeCodesCat();
	}


}
